### ISSUE TITLE
text-1.2.1.0 compatibility

### ISSUE THREAD

**Issue by peti** [kawu/text-binary#2]
The latest release of `text` provides binary instances that collide with the ones in this package:

```
Data/Text/Binary.hs:12:10:
    Duplicate instance declarations:
      instance Binary T.Text -- Defined at Data/Text/Binary.hs:12:10
      instance Binary T.Text -- Defined in ‘Data.Text’

Data/Text/Binary.hs:16:10:
    Duplicate instance declarations:
      instance Binary L.Text -- Defined at Data/Text/Binary.hs:16:10
      instance Binary L.Text -- Defined in ‘Data.Text.Lazy’
```

Cited from http://hydra.cryp.to/build/884302/log/raw.

Is there maybe a way to triage this situation somehow, i.e. by making `text-binary` just forward those definitions if the underlying version of `text` is sufficiently recent?

**Comment by bergmark** [comment]
https://github.com/kawu/text-binary/pull/1
